version: '3.2'
services:
  # 서비스 명
  postgresql:
    # 사용할 이미지
    image: postgres
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너 명
    container_name: postgres
    # 접근 포트 설정 (외부:내부)
    ports:
      - '5432:5432'
    # 환경 변수 설정
    environment:
      # PG 계정 및 패스워드
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto1
      POSTGRES_DB: crypto-checker
      TZ: Asia/Seoul
    # 볼륨 설정
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
