"""Add Chain Model.

Revision ID: 027bed143517
Revises: 915e57f2f743
Create Date: 2025-03-01 23:10:41.332449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "027bed143517"
down_revision: Union[str, None] = "915e57f2f743"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chain",
        "name",
        existing_type=sa.VARCHAR(),
        comment="체인 이름",
        existing_nullable=False,
    )
    op.alter_column(
        "chain",
        "image",
        existing_type=sa.VARCHAR(),
        comment="체인 이미지",
        existing_nullable=False,
    )
    op.alter_column(
        "chain",
        "home_page",
        existing_type=sa.VARCHAR(),
        comment="홈페이지",
        existing_nullable=False,
    )
    op.alter_column(
        "chain",
        "discord",
        existing_type=sa.VARCHAR(),
        comment="디스코드 주소",
        existing_nullable=True,
    )
    op.alter_column(
        "chain",
        "twitter",
        existing_type=sa.VARCHAR(),
        comment="트위터 주소",
        existing_nullable=True,
    )
    op.alter_column(
        "chain",
        "twitter_handle",
        existing_type=sa.VARCHAR(),
        comment="트위터 핸들",
        existing_nullable=True,
    )
    op.alter_column(
        "chain",
        "contract",
        existing_type=sa.VARCHAR(),
        comment="체인 계약 주소",
        existing_nullable=False,
    )
    op.alter_column(
        "chain",
        "is_test",
        existing_type=sa.BOOLEAN(),
        comment="테스트 여부",
        existing_nullable=False,
    )
    op.alter_column(
        "wallet",
        "name",
        existing_type=sa.VARCHAR(),
        comment="지갑 이름",
        existing_nullable=True,
    )
    op.alter_column(
        "wallet",
        "address",
        existing_type=sa.VARCHAR(),
        comment="지갑 주소",
        existing_nullable=False,
    )
    op.alter_column(
        "wallet",
        "user_id",
        existing_type=sa.UUID(),
        comment="유저 id",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wallet",
        "user_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="유저 id",
        existing_nullable=False,
    )
    op.alter_column(
        "wallet",
        "address",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="지갑 주소",
        existing_nullable=False,
    )
    op.alter_column(
        "wallet",
        "name",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="지갑 이름",
        existing_nullable=True,
    )
    op.alter_column(
        "chain",
        "is_test",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="테스트 여부",
        existing_nullable=False,
    )
    op.alter_column(
        "chain",
        "contract",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="체인 계약 주소",
        existing_nullable=False,
    )
    op.alter_column(
        "chain",
        "twitter_handle",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="트위터 핸들",
        existing_nullable=True,
    )
    op.alter_column(
        "chain",
        "twitter",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="트위터 주소",
        existing_nullable=True,
    )
    op.alter_column(
        "chain",
        "discord",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="디스코드 주소",
        existing_nullable=True,
    )
    op.alter_column(
        "chain",
        "home_page",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="홈페이지",
        existing_nullable=False,
    )
    op.alter_column(
        "chain",
        "image",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="체인 이미지",
        existing_nullable=False,
    )
    op.alter_column(
        "chain",
        "name",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="체인 이름",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
