"""JoinedMission Add Column joined_at

Revision ID: 46dd0e82f3c0
Revises: b0b9d767aed8
Create Date: 2025-03-12 09:33:10.528857

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46dd0e82f3c0"
down_revision: Union[str, None] = "b0b9d767aed8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "joined_mission", sa.Column("joined_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("joined_mission", "joined_at")
    # ### end Alembic commands ###
