"""Add Models

Revision ID: 48f8a04dea68
Revises: e46639c5921c
Create Date: 2025-03-05 15:02:56.476916

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "48f8a04dea68"
down_revision: Union[str, None] = "e46639c5921c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "layer",
        existing_type=postgresql.ENUM("L1", "L2", "L3", name="layer"),
        nullable=False,
        existing_comment="L1,L2,L3",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "layer",
        existing_type=postgresql.ENUM("L1", "L2", "L3", name="layer"),
        nullable=True,
        existing_comment="L1,L2,L3",
    )
    # ### end Alembic commands ###
