"""datetime issue

Revision ID: 4f6740cd104c
Revises: 8b8314de08e3
Create Date: 2025-03-02 10:43:55.733703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f6740cd104c"
down_revision: Union[str, None] = "8b8314de08e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "announcement", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("announcement", "created_at")
    # ### end Alembic commands ###
