"""Modify Project Column

Revision ID: 5a7cd34fa804
Revises: a1636bf54f0d
Create Date: 2025-03-14 11:17:08.206967

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a7cd34fa804"
down_revision: Union[str, None] = "a1636bf54f0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "test_contract",
        existing_type=sa.VARCHAR(),
        type_=sa.Boolean(),
        nullable=False,
        existing_comment="테스트 계약 여부",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "test_contract",
        existing_type=sa.Boolean(),
        type_=sa.VARCHAR(),
        nullable=True,
        existing_comment="테스트 계약 여부",
    )
    # ### end Alembic commands ###
