"""Add Chain Model.

Revision ID: 915e57f2f743
Revises: ec98af43a464
Create Date: 2025-03-01 23:06:50.038235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "915e57f2f743"
down_revision: Union[str, None] = "ec98af43a464"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chain",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("image", sa.String(), nullable=False),
        sa.Column("home_page", sa.String(), nullable=False),
        sa.Column("discord", sa.String(), nullable=True),
        sa.Column("twitter", sa.String(), nullable=True),
        sa.Column("twitter_handle", sa.String(), nullable=True),
        sa.Column("contract", sa.String(), nullable=False),
        sa.Column("is_test", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contract"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chain")
    # ### end Alembic commands ###
