"""Project Model Remove and Add Column

Revision ID: a1636bf54f0d
Revises: 46dd0e82f3c0
Create Date: 2025-03-12 15:19:50.061015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1636bf54f0d"
down_revision: Union[str, None] = "46dd0e82f3c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("git_hub", sa.String(), nullable=True, comment="프로젝트 깃헙"),
    )
    op.drop_column("project", "layer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "layer",
            postgresql.ENUM("L1", "L2", "L3", name="layer"),
            autoincrement=False,
            nullable=False,
            comment="L1,L2,L3",
        ),
    )
    op.drop_column("project", "git_hub")
    # ### end Alembic commands ###
