"""User Model Modify Column JoinedMission

Revision ID: a71d13df5922
Revises: b7956b8ba590
Create Date: 2025-03-06 08:51:23.986075

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a71d13df5922"
down_revision: Union[str, None] = "b7956b8ba590"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
