"""Add

Revision ID: a74f013707e7
Revises: ae3aaa98922b
Create Date: 2025-03-02 10:23:27.817172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a74f013707e7"
down_revision: Union[str, None] = "ae3aaa98922b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcement",
        sa.Column(
            "sequence_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="시퀀스 번호",
        ),
        sa.Column("title", sa.String(), nullable=False, comment="제목"),
        sa.Column("content", sa.String(), nullable=False, comment="본문"),
        sa.PrimaryKeyConstraint("sequence_id"),
    )
    op.create_table(
        "mission",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "type",
            sa.Enum("WAIT_LIST", "WHITE_LIST", "VAULT", "QUEST", name="missiontype"),
            nullable=False,
            comment="미션 종류",
        ),
        sa.Column("title", sa.String(), nullable=False, comment="제목"),
        sa.Column("url", sa.String(), nullable=False, comment="미션 페이지 URL"),
        sa.Column(
            "participation_start_at",
            sa.DateTime(),
            nullable=False,
            comment="참여 시작 시간",
        ),
        sa.Column(
            "participation_end_at",
            sa.DateTime(),
            nullable=False,
            comment="참여 종료 시간",
        ),
        sa.Column("draw_at", sa.DateTime(), nullable=True, comment="추첨 시간"),
        sa.Column("reward_date", sa.Date(), nullable=True, comment="보상 시간"),
        sa.Column("project_id", sa.Uuid(), nullable=False, comment="프로젝트 id"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mission")
    op.drop_table("announcement")
    # ### end Alembic commands ###
