"""Add Models

Revision ID: ae3aaa98922b
Revises: b7b1dbed369f
Create Date: 2025-03-02 10:19:31.821387

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae3aaa98922b"
down_revision: Union[str, None] = "b7b1dbed369f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "is_test_contract", sa.Boolean(), nullable=False, comment="테스트 계약 여부"
        ),
    )
    op.drop_column("project", "is_test")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "is_test",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="테스트 여부",
        ),
    )
    op.drop_column("project", "is_test_contract")
    # ### end Alembic commands ###
