"""mapped str -> uuid.UUID

Revision ID: b0b9d767aed8
Revises: cb6605c864c2
Create Date: 2025-03-09 20:46:44.787079

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b0b9d767aed8"
down_revision: Union[str, None] = "cb6605c864c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
