"""User Model Add Column sub_id

Revision ID: b7956b8ba590
Revises: d119ff520088
Create Date: 2025-03-06 08:30:51.742892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7956b8ba590"
down_revision: Union[str, None] = "d119ff520088"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("sub_id", sa.String(), nullable=False, comment="GOOGLE_SUB_ID"),
    )
    op.add_column(
        "user",
        sa.Column(
            "reward_notification",
            sa.Boolean(),
            nullable=False,
            comment="리워드 알림 설정",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "reward_notification")
    op.drop_column("user", "sub_id")
    # ### end Alembic commands ###
