"""Remove Chain Model

Revision ID: b7b1dbed369f
Revises: 027bed143517
Create Date: 2025-03-01 23:56:05.197624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7b1dbed369f"
down_revision: Union[str, None] = "027bed143517"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False, comment="체인 이름"),
        sa.Column("image", sa.String(), nullable=False, comment="체인 이미지"),
        sa.Column("home_page", sa.String(), nullable=False, comment="홈페이지"),
        sa.Column("discord", sa.String(), nullable=True, comment="디스코드 주소"),
        sa.Column("twitter", sa.String(), nullable=True, comment="트위터 주소"),
        sa.Column("twitter_handle", sa.String(), nullable=True, comment="트위터 핸들"),
        sa.Column("contract", sa.String(), nullable=False, comment="체인 계약 주소"),
        sa.Column("is_test", sa.Boolean(), nullable=False, comment="테스트 여부"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contract"),
    )
    op.drop_table("chain")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chain",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="체인 이름",
        ),
        sa.Column(
            "image",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="체인 이미지",
        ),
        sa.Column(
            "home_page",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="홈페이지",
        ),
        sa.Column(
            "discord",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="디스코드 주소",
        ),
        sa.Column(
            "twitter",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="트위터 주소",
        ),
        sa.Column(
            "twitter_handle",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="트위터 핸들",
        ),
        sa.Column(
            "contract",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="체인 계약 주소",
        ),
        sa.Column(
            "is_test",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="테스트 여부",
        ),
        sa.PrimaryKeyConstraint("id", name="chain_pkey"),
        sa.UniqueConstraint("contract", name="chain_contract_key"),
    )
    op.drop_table("project")
    # ### end Alembic commands ###
