"""JoinedMission Column 수정

Revision ID: cb6605c864c2
Revises: f80203a23d7f
Create Date: 2025-03-09 20:39:52.557495

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb6605c864c2"
down_revision: Union[str, None] = "f80203a23d7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "joined_mission",
        sa.Column("wallet_id", sa.Uuid(), nullable=False, comment="지갑 id"),
    )
    op.drop_constraint(
        "joined_mission_user_id_fkey", "joined_mission", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "joined_mission", "wallet", ["wallet_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("joined_mission", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "joined_mission",
        sa.Column(
            "user_id", sa.UUID(), autoincrement=False, nullable=False, comment="미션 id"
        ),
    )
    op.drop_constraint(None, "joined_mission", type_="foreignkey")
    op.create_foreign_key(
        "joined_mission_user_id_fkey",
        "joined_mission",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("joined_mission", "wallet_id")
    # ### end Alembic commands ###
