"""add column wallet type

Revision ID: f80203a23d7f
Revises: a71d13df5922
Create Date: 2025-03-08 18:03:35.664476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f80203a23d7f"
down_revision: Union[str, None] = "a71d13df5922"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallet",
        sa.Column(
            "type",
            sa.Enum(
                "METAMASK",
                "PHANTOM",
                "SUI",
                "BACK_PACK",
                "OKX",
                "BINANCE",
                name="wallettype",
            ),
            nullable=False,
            comment="지갑 종류",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallet", "type")
    # ### end Alembic commands ###
